blank_issues_enabled: true
contact_links:
  - name: Ask a question or get support
    url: https://join.slack.com/t/nixtlacommunity/shared_invite/zt-1h77esh5y-iL1m8N0F7qV1HmH~0KYeAQ
    about: Ask a question or request support for using a library of the nixtlaverse
